= pack library for conan

. copy `conan` directory from templates to project root
. edit `conan/conanfile.py`
.. edit class name accordingly
.. edit value of class's static variable `name`
.. edit value of class's static variable `description`
.. add package dependencies to `def requirements(self):` method
. edit `conan/test_package/example.cpp` to a simple usage of the library
. conan will inject dependency compilation/linking flags via `CXXFLAGS`/`LDFLAGS` etc. envirnoment variables. Most likely,
  static linking will be in use with conan packages, but in case of dynamic linking it is needed to add paths to `LD_LIBRARY_PATH` for running test apps.
  This can be done by getting paths from `LDFLAGS` variable. `this_test_ld_path += $(patsubst -L%,%,$(filter -L%,$(LDFLAGS)))`
. edit CI
.. add conan jobs
.. add conan env vars
.. check that `PACKAGE_VERSION` is set to commit hash by default
.. check that `PACKAGE_VERSION` is passed in to `conan create` command via `--version` command line argument
