= Pack library to vcpkg

. copy `templates/cmake` directory as is to the library repo `build/` directory and add it to git.
. copy the `templates/vcpkg` directory as is to the library repo `build/` and add it to git.
. resolve `TODO:`-s in all the files of the `vcpkg` and `cmake` directories.
. add `vcpkg` job to the `.github/workflows/ci.yml`:
+
....
##### vcpkg-linux #####
  vcpkg-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: debian, codename: bookworm, image_owner: }
          # - {os: debian, codename: bookworm, image_owner: i386/, labels: [i386,docker]}
          # - {os: debian, codename: bookworm, image_owner: arm32v7/, labels: [ubuntu-24.04-arm]}
          # - {os: debian, codename: bookworm, image_owner: arm64v8/, labels: [ubuntu-24.04-arm]}
    runs-on: ${{ (matrix.labels == '' && 'ubuntu-latest') || matrix.labels }}
    container: ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    name: vcpkg - linux | ${{ matrix.image_owner }}
    steps:
      - name: add cppfw deb repo
        uses: myci-actions/add-deb-repo@main
        with:
          repo: deb https://gagis.hopto.org/repo/cppfw/${{ matrix.os }} ${{ matrix.codename }} main
          repo-name: cppfw
          keys-asc: https://gagis.hopto.org/repo/cppfw/pubkey.gpg
          install: myci cmake git curl zip unzip tar nodejs pkg-config
      - name: git clone
        uses: myci-actions/checkout@main
      - name: install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg-installation
          (cd vcpkg-installation; ./bootstrap-vcpkg.sh)
      - name: set VCPKG_ROOT
        uses: myci-actions/export-env-var@main
        with: {name: VCPKG_ROOT, value: "$(pwd)/vcpkg-installation"}
      - name: add VCPKG_ROOT to PATH
        uses: myci-actions/export-env-var@main
        with: {name: PATH, value: "$PATH:$VCPKG_ROOT"}
      - name: prepare vcpkg port
        run: |
          myci-vcpkg-prepare.sh --vcpkg-dir build/vcpkg --git-ref ${{ github.sha }}
      - name: test vcpkg port
        run: |
          cd build/vcpkg/test
          cmake .
          make
          ./test
      - name: upload vcpkg logs to artifacts
        if: always() # even if previous steps fail, this one needs to be run
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg_logs
          path: |
            vcpkg-installation/buildtrees/${{ env.PACKAGE_NAME }}/
            build/vcpkg/**/*.log
      - name: deploy vcpkg port
        run: |
          myci-deploy-vcpkg.sh --repo cppfw/vcpkg-repo --port-dir build/vcpkg/overlay/${PACKAGE_NAME}
        if: startsWith(github.ref, 'refs/tags/')
##### vcpkg-windows #####
  vcpkg-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    name: vcpkg - windows
    steps:
    - name: git clone
      uses: actions/checkout@v4
    - name: get myci scripts
      uses: actions/checkout@v4
      with:
        repository: cppfw/myci
        ref: latest
        path: myci
    - name: add myci to PATH
      uses: myci-actions/export-env-var-powershell@main
      with: {name: PATH, value: "$env:Path;myci/src/powershell"}
    - name: set VCPKG_ROOT
      uses: myci-actions/export-env-var-powershell@main
      # accorging to github actions windows image docs, it should define VCPKG_INSTALLATION_ROOT env var,
      # but on practice it is not set, so specify vcpkg root path explicitly
      with: {name: VCPKG_ROOT, value: "C:/vcpkg/"}
    - name: prepare vcpkg port
      run: myci-vcpkg-prepare.ps1 -gitref ${{ github.sha }}
    - name: test vcpkg port
      run: |
        cd build/vcpkg/test
        cmake .
        cmake --build . --parallel
        ./Debug/test.exe
    - name: upload vcpkg logs to artifacts
      if: always() # even if previous steps fail, this one needs to be run
      uses: actions/upload-artifact@v4
      with:
        name: vcpkg_windows_logs
        path: |
          vcpkg-installation/buildtrees/${{ env.PACKAGE_NAME }}/
          build/vcpkg/**/*.log
....