= Pack library to vcpkg

. copy `templates/vcpkg/cmake` directory as is to the library repo `build/vcpkg` directory and add it to git.
. copy the `templates/vcpkg/vcpkg` directory as is to the library repo `build/vcpkg` and add it to git.
. resolve the `TODO:`s in all the files of the `vcpkg` dir
. add `vcpkg` job to the `.github/workflows/ci.yml`:
+
....
##### vcpkg #####
  vcpkg:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: debian, codename: bookworm, image_owner: }
          # - {os: debian, codename: bookworm, image_owner: i386/, labels: [i386,docker]}
          # - {os: debian, codename: bookworm, image_owner: arm32v7/, labels: [ubuntu-24.04-arm]}
          # - {os: debian, codename: bookworm, image_owner: arm64v8/, labels: [ubuntu-24.04-arm]}
    runs-on: ${{ (matrix.labels == '' && 'ubuntu-latest') || matrix.labels }}
    container: ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.codename }}
    name: vcpkg - linux | ${{ matrix.image_owner }}
    steps:
      - name: add cppfw deb repo
        uses: myci-actions/add-deb-repo@main
        with:
          repo: deb https://gagis.hopto.org/repo/cppfw/${{ matrix.os }} ${{ matrix.codename }} main
          repo-name: cppfw
          keys-asc: https://gagis.hopto.org/repo/cppfw/pubkey.gpg
          install: myci cmake git curl zip unzip tar nodejs pkg-config
      - name: git clone
        uses: myci-actions/checkout@main
      - name: install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg-installation
          (cd vcpkg-installation; ./bootstrap-vcpkg.sh)
      - name: set VCPKG_ROOT
        uses: myci-actions/export-env-var@main
        with: {name: VCPKG_ROOT, value: "$(pwd)/vcpkg-installation"}
      - name: add VCPKG_ROOT to PATH
        uses: myci-actions/export-env-var@main
        with: {name: PATH, value: "$PATH:$VCPKG_ROOT"}
      - name: prepare vcpkg port
        run: |
          myci-vcpkg-prepare.sh --vcpkg-dir build/vcpkg --git-ref ${{ github.sha }}
      - name: test vcpkg port
        run: |
          cd build/vcpkg/test
          cmake .
          make
          ./test
      - name: upload vcpkg logs to artifacts
        if: always() # even if previous steps fail, this one needs to be run
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg_logs
          path: |
            vcpkg-installation/buildtrees/${{ env.PACKAGE_NAME }}/
            build/vcpkg/**/*.log
      - name: deploy vcpkg port
        run: |
          myci-deploy-vcpkg.sh --repo cppfw/vcpkg-repo --port-dir vcpkg/overlay/${PACKAGE_NAME}
        if: startsWith(github.ref, 'refs/tags/')
....